### ISSUE TITLE
[Feature request] Set Minimum Recording Interval to 1 sec by default

### ISSUE THREAD

**Issue by mrk2005** [CellMapper/CellMapper-Android-App#10]
As the title says. Could you please set to 1 second the minimum recording interval? The trails would be a lot more precise. Thanks!

**Comment by olkitu** [comment]
Change default interval from 5 second to 1 second.

**Comment by mrk2005** [comment]
Yes, I do it every time I re-install the app.. But the common user doesn't even know what it's referred to, and leave it to 5. What I'm asking is to set it to 1 By Default, so when anyone install the app it is already set.

**Comment by zivan56** [comment]
This will increase the amount of data significantly.  It should only be enabled by advanced users who know how to use it properly.
