### ISSUE TITLE
Cellmapper with an inactive SIM card : Showing cell data

### ISSUE THREAD

**Issue by brycenesbitt** [CellMapper/CellMapper-Android-App#101]
# Impact Version
* Phone Model: Google Pixel
* Language: en

I've inserted an inactive SIM in a phone.  Cellmapper
appears to be collecting data normally, however the "Cells" tab
shows no cell info.  The "Map" tab shows a 2G cell ID.

Dialing *#*#4636#*#* brings up a phone status menu outside of cellmapper, which shows the current cell ID, with data "disconnected".

Is it possible for Cellmapper to be expanded to fully work with inactive SIMs?

**Comment by olkitu** [comment]
If Cell ID API report information without SIM or inactive SIM should work. I still recommended have active plan like some Prepaid on phone.
