### ISSUE TITLE
Issue with Magisk

### ISSUE THREAD

**Issue by sataevr** [CellMapper/CellMapper-Android-App#105]
Xiaomi Redmi 4 Prime, Android 6.0, app v5.2.3, latest stable Magisk.

Phone hard reboot when app start second time with Magisk root. First run with Magisk; every run with SuperSU — everything fine. Network Signal Guru and other root apps with Magisk fine too.

**Comment by olkitu** [comment]
Please do not use Qualcomm Root mode on your phone. Seems it does not work properly on your device.

**Comment by sataevr** [comment]
> Please do not use

Why? All collected data 100% valid. I checked and double checked it in NSG and CellMapper. Just fix it. ;)

**Comment by olkitu** [comment]
NSG use different method than Cellmapper App. Cellmapper use mostly Android own API and that Qualcomm Reading method is deprecated because Android native Cell ID API offer A/U/EARFN already since Android 7.0.
