### ISSUE TITLE
Allow mark on app "Tower is here"

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#109]
Locate tower via app - when example have -60dBm signal so then could mark "Tower is here" and it will save info in web map.

**Comment by brycenesbitt** [comment]
I'd like to mark towers, even if I don't know what carrier uses them.

**Comment by olkitu** [comment]
Tower movement adopted in latest BETA version of CM App 5.4.0

**Comment by brycenesbitt** [comment]
Not tower movement.
The ability to mark a tower you see on the ground, before you know which carrier is using it.

**Comment by olkitu** [comment]
This feature is not possible add to CM. You have to record it with CM first

**Comment by brycenesbitt** [comment]
Of course it is possible to add to CM.
