### ISSUE TITLE
[Issue] OnePlus 3 Dual SIM not working

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#11]
When use Dual SIM On + API 4.2, report wrong data.

When use Dual SIM On + Old API report double time same Cell.

**Comment by zivan56** [comment]
Dual SIM ON + API 4.2 is not allowed in the new app

**Comment by veixes** [comment]
Oneplus3 Android 7 with new API

![g6h5pph](https://cloud.githubusercontent.com/assets/22761625/20791485/e9583bea-b7c5-11e6-9e19-69bc23b6a1fd.png)
