### ISSUE TITLE
Led flashing during record

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#112]
Flash led during active data recording 

- Option to App setting turn on / off
- Flahing colour maybe neutral: cyan, magenta, white

**Comment by RistiCore** [comment]
Seems like version 5.3.0 from 1st of July brings this feature into app and FR may be closed?

**Comment by olkitu** [comment]
Yes this feature added latest 5.3.0 and on Android Settings -> Apps -> Cellmapper can change LED notification settings.
