### ISSUE TITLE
Some phone have upload issue

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#16]
Latest App version 5.X.

Some phone's have lagging issue uploading data to server.  Someone report activity lagging or get uploas error. 

Few step what you can try:
* First try use Map on App. Working? If lagging try disable IPv6, someone have issue for that.
* If you updated from App version 4.X, try clear data

Please post here if you have similar issue.

**Comment by dbergamini** [comment]
Nexus 6 user on Project Fi. I never had a problem bulk uploading before the 5.x upgrade recently. Shortly after the upgrade, I was receiving frequent Error 5, something about the database being locked for update. I registered on cellmapper.net finally, but was still getting the error. That went away a few days later.

I noticed in the previous version there used to be a lag when clicking on the menu and then selecting the Upload and Statistics menu (when you pressed on it, it would half-retract the menu and hang). Now when you click the Upload and Statistics menu it loads instantly, but displays Loading... in the body of the page. Clicking the "Upload" icon in the upper left is slow to display the "Uploading 101 data points" and the app hangs frequently on the screen with regular pop-ups that the app is not responding (wait or OK to kill).

Clicking the Upload button, waiting for it to start uploading, and switching to map screen makes a significant improvement on the upload performance, and overall usability of the phone while uploading. Thanks for the hint, it was getting very frustrating.

Daniel

**Comment by olkitu** [comment]
Thansk @dbergamini for your message. Your issue seems different. Do you have try clear app data after update?

**Comment by dbergamini** [comment]
@olkitu,

I was able to upload a ton of data points while on the map screen, I wanted to make sure it was fully synced. I cleared app data and my local million or so data points are now gone. The app does perform a lot quicker now. I'll check back in if it continues to be a problem. Thanks!

Daniel

**Comment by olkitu** [comment]
Now we have disabled IPv6 on server. Someone have routing issue to Cellmapper server via IPv6.
