### ISSUE TITLE
Add top of the Advertisement title: "Advertisement"

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#17]
I would like to suggest that you add some clear label above the add box saying "Advertisement" or something like that.

**Comment by zivan56** [comment]
The ads are standard Adsense ads.  If you think an ad is deceptive, there is a button in the corner of the ad you can tap to report.
This will use even more screen real estate and will cover the sides of the ad which reduces the map visible area.  Will not add this.
