### ISSUE TITLE
Samsung Galaxy S7 G930T report wrong BW when LTE-CA showing

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#31]
Issue reporting LTE-CA data from Service Mode G930T. 

![photo_2016-10-08_01-16-19](https://cloud.githubusercontent.com/assets/10426342/19206898/d8530786-8cf4-11e6-8f74-0148a37f8029.jpg)

![photo_2016-10-08_01-16-52](https://cloud.githubusercontent.com/assets/10426342/19206908/eca6ee3c-8cf4-11e6-8a09-8540c457fbbe.jpg)

**Comment by zivan56** [comment]
I am assuming this is the root reader, as I don't see any way it can be an issue with the screen reader.  It will be fixed in the next beta.

**Comment by andsy265** [comment]
I've had a similar problem on my S7 SM-G930F, I've logged a mast as Band 2 rather than band 3 for EE in the UK. This was not from the root reader as it's not enabled and my phone isn't rooted.

**Comment by olkitu** [comment]
Reading from Service mode is deprecated feature, since Samsung implemented API 4.2+ in Android 8.0.
