### ISSUE TITLE
Add the possibility to add tower coordinates manually

### ISSUE THREAD

**Issue by mrk2005** [CellMapper/CellMapper-Android-App#41]
Hi, I have a xls file with the coordinates (in gauss-boaga, unfortunately) of the towers in the region i live. When I have to move a tower, I need to convert gauss-boaga to WGS84 using this site: http://www.ultrasoft3d.net/Conversione_Coordinate.aspx and then search to the map the exact point to move the tower into, and move the tower.
Could you please add a little form so that once i selected the tower, on two fields for gauss boaga coordinates, i can put coordinates there and the tower automatically locate itself?

**Comment by zivan56** [comment]
A form would be open to abuse.  If you send me a CSV with latitude/longitude/CID (or eNB ID) in separate fields I can import it.  Likewise, if it has site names and extra metadata, they can be included as a separate column and can be automatically added to the extra data.

**Comment by marcoGardellini** [comment]
Thanks for the offer, but my CSV file doesn't have enB nor CID, it only has a "site id" (that sometimes matches with the 3G CID, sometimes don't) with a physical address and the gauss-boaga coordinates. I have to match the "site id"/address manually, but it would be easier for me to have a form where put coordinates into. 
We also have a user (gially86) who has access to the complete DB of the Italian towers, so I think he would be REALLY pleased to have a form like this (I think he uses normal WGS84 or WGS GD coordinates). Couldn't you open this little form only for me and him? mrk2005 and gially86? I promise you i'll use it carefully :P Thanks!!

**Comment by mrk2005** [comment]
Thanks for the offer, but my CSV file doesn't have enB nor CID, it only has a "site id" (that sometimes matches with the 3G CID, sometimes don't) with a physical address and the gauss-boaga coordinates. I have to match the "site id"/address manually, but it would be easier for me to have a form where put coordinates into. 
We also have a user (gially86) who has access to the complete DB of the Italian towers, so I think he would be REALLY pleased to have a form like this (I think he uses normal WGS84 or WGS GD coordinates). Couldn't you open this little form only for me and him? mrk2005 and gially86? I promise you i'll use it carefully :P Thanks!!

**Comment by olkitu** [comment]
eNB you can calculate from CID.

**Comment by mrk2005** [comment]
But I don't have CID either

**Comment by olkitu** [comment]
Then how to add coordinate to right tower if you do not know CID?

**Comment by olkitu** [comment]
Okay maybe add form on map where you can put new coordinate... Maybe that working...

**Comment by mrk2005** [comment]
Basically I search it on the map (I have a map too: http://map.arpa.veneto.it/website/etere_www2/viewer.htm?SERVICE=etere_new&ActiveLayer=10&Queryzoom=Yes&Query=PROVINCIA%3D%27TV%27) and when I'm sure of what site is, I fetch coordinates from the CSV/excel file and convert them, insert them on cellmapper, zoom a lot, try to locate the site in there, etc. But gially86 has enB too

**Comment by zivan56** [comment]
You can use the search box on the side and enter latitude,longitude
It will place a new marker on the map.  You can move the tower to this location.
