### ISSUE TITLE
Recording data every second doesn't really work

### ISSUE THREAD

**Issue by mrk2005** [CellMapper/CellMapper-Android-App#42]
Hi, on all my devices, even if I set minimum recording interval to 1 sec, it records about every 3 seconds, so the trail isn't much accurate...

**Comment by olkitu** [comment]
What device you have? I recommended you post your device. Plus depends your speed, if you walk not need really every second and on highway no one care see what color you see every meter :+1:

**Comment by mrk2005** [comment]
It happens on Asus ME302KL with Android 4.2, Moto g 4g xt1039 with CM13 (MM), Lg G3 D855 with CM13 too. On highway it results in a point every 108mt, not exactly every meter...

**Comment by zivan56** [comment]
The code that deals with this hasn't changed in months, if not years.  I would suggest enabling CSV writing or if you are rooted to read the internal database to see how often it is recorded.

**Comment by zivan56** [comment]
Since there was no feedback or CSV provided, I am closing this as not a bug as it has a timer to record data depending on what setting you choose.
