### ISSUE TITLE
Add the red marker (like google) when typing the exact coordinates

### ISSUE THREAD

**Issue by marcoGardellini** [CellMapper/CellMapper-Android-App#55]
When I search for GPS coordinates like 46.440972 12.054633 in the Location tab on the website, would be nice if it put a marker on the exact point of the map, not only centering the map. 
When I insert coordinates on google map search, it locate a marker too on the exact point.. Would be nice if cellmapper did it too.

**Comment by zivan56** [comment]
This isn't an app issue, it has no location search.
I have put this feature on the map as requested.
