### ISSUE TITLE
Show current band in the driving mode

### ISSUE THREAD

**Issue by Purnipsi** [CellMapper/CellMapper-Android-App#56]
Please, add info line displaying the currently serving band (data provided by advanced data logging measures) or via recorded data from the database. I think that a band number is informative enough, showing megahertz would be too complicated.

![featreg](https://cloud.githubusercontent.com/assets/21300958/20040069/75386fc0-a459-11e6-86fb-f93a9dfc1a2b.jpg)

**Comment by zivan56** [comment]
It already does this in the way described when it knows the exact frequency.
I'll fix it so that it works for estimated bands as well in the next beta build.

**Comment by Purnipsi** [comment]
@zivan56 "It already does this in the way described when it knows the exact frequency."

I haven't seen that happening so far, this specific base station has exact band information, but it's not showing the band info on drive mode.

It's glad to hear you are working on improving the app. :)

**Comment by olkitu** [comment]
On Latest BETA this is fixed.

**Comment by Purnipsi** [comment]
Yep, the bug is fixed.
