### ISSUE TITLE
topUsers page occasionally displays wrong info

### ISSUE THREAD

**Issue by veixes** [CellMapper/CellMapper-Android-App#59]
http://www.cellmapper.net/topUsers
Page occassionally displays wrong info about towers/moved. also points uploaded, towers detected is sometimes wrong.

For certain, i know that my (veixes) towers moved/deleted should be over 3000
![17112016_1505gmtplus2](https://cloud.githubusercontent.com/assets/22761625/20390458/a30039ca-acd7-11e6-977b-32a8d7a78c95.JPG)

**Comment by marcoGardellini** [comment]
About this: the user gially86 reports that there's definitely something wrong with the moved tower, that according to this new disposition he "would have moved 2000 towers more than once", which is not possibile. Also, if you order by "Towers moved/deleted", the order is not correct, at some point the data get mixed. (Try that!).

**Comment by veixes** [comment]
Also.
When checking the "cells discovered" column, my numbers seem to fluctuate by many thousand cells.
Currently it displays as ~14,480 or ~16800

Also the sorting in towers moved/deleted uses the thousand separator comma as a decimal places separator.

**Comment by zivan56** [comment]
So this only happens sometimes?  Is it sometime correct and sometimes not?

**Comment by veixes** [comment]
For me it seems that towers discovered  number fluctuates by tower count that have recently updated(location being calculated). 

So if 10 towers that I have discovered before, get new data from me or from somebody else then this 10 gets taken off from my count until updating is finished. 

2nd issue is the cosmetic sorting issue in towers moved column.

**Comment by zivan56** [comment]
The sorting issue has been fixed.

This is not something that is real time, it is essentially a low priority task that runs a few times a day and may fail sometimes.  Even as it is now, it uses way too much resources for the amount of use it gets.
