### ISSUE TITLE
5.0.7 "Unfortunately, CellMapper has stopped."

### ISSUE THREAD

**Issue by Bryan48765** [CellMapper/CellMapper-Android-App#66]
After scrolling down, scrolling up on the cell list.
With valid 4G cells(logcat reader), and with invalid -51dbms.
I/am_crash(2703): [11727,0,cellmapper.net.cellmapper,949534276,java.lang.NullPointerException,Attempt to invoke virtual method 'void android.widget.ImageView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference,NULL,-1]

**Comment by olkitu** [comment]
Do you have sended feedback when that dialog appear and add description what hapening? Add also your nick.

**Comment by Bryan48765** [comment]
After scrolling down, scrolling up on the cell list.
With valid 4G cells(logcat reader), and with invalid -51dbms.
I/am_crash(2703): [11727,0,cellmapper.net.cellmapper,949534276,java.lang.NullPointerException,Attempt to invoke virtual method 'void android.widget.ImageView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference,NULL,-1]

**Comment by olkitu** [comment]
Thank you, developer will cach this issue.

**Comment by zivan56** [comment]
What OS and Phone?

**Comment by Bryan48765** [comment]
samsung|SM-A510F|6.0.1|MMB29K

**Comment by olkitu** [comment]
Please try new beta, will be available Google Play

**Comment by zivan56** [comment]
Please download the latest beta just released, this should fix the issue.

**Comment by Bryan48765** [comment]
It's fixed in the latest update.

**Comment by olkitu** [comment]
I heard same from other user. I will now close this case.
