### ISSUE TITLE
CellMapper App freez / crash when try upload

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#67]
When try manual uploading app freez and then crash.  Also sometime crashing hapening on cell screen. 

![photo_2017-01-08_19-43-51](https://cloud.githubusercontent.com/assets/10426342/21752069/d120b66e-d5da-11e6-9f44-a2b01b3ada93.jpg)

Device: Motorola Moto G4 Plus
OS: Android 7.0 NPJ25.93-11

If you get similar freez / crash or something, please comment to this issue. Also send always feedback and add your nick there (Tell us about your issue here so we can track that).

**Comment by VSlavskiy** [comment]
Same problem on Huawei Y536-A1. Android 4.4.3, rooted. Sometimes it uploads successfully if I leave it alone for long enough, and other times the app crashes.
Have not observed this issue on Samsung Galaxy S7 with Android 7.0 NRD90M

**Comment by olkitu** [comment]
Try put upload patch size to "10" under Settings. That helps me.

**Comment by zivan56** [comment]
Should be fixed in latest beta.
