### ISSUE TITLE
Feature request : remember username , eventually pasword

### ISSUE THREAD

**Issue by alinderom** [CellMapper/CellMapper-Android-App#70]
Hello,
I would like to request the following fetaure in CellMapper
- remember username, eventually password , and eventually auto-login

Is this possible? It would make working with it a lot easier

Thanks,
A. Derom

**Comment by olkitu** [comment]
Hi, on app? It should remember when you have connection and relogin. If you do not have network or some network issues when you launch app, try restart app.

**Comment by alinderom** [comment]
Hi, you are correct. But it takes a while before the red account icon becomes green.  Now that I know this I'll wait a minute before checking it.
Thanks for your help.
