### ISSUE TITLE
What bandthwidth is 2G/3G/4G

### ISSUE THREAD

**Issue by alinderom** [CellMapper/CellMapper-Android-App#73]
on the map website of cellmapper you can choose what bandtwidth you want to show 2G(=GSM), 3G(=UMTS) & 4G(=LTE).
But on most cellphones (mine is a Samsung GTi-9195 (S4mini)) you have names like LTE, WCDMA, GSM, 
Many moire can be found on https://en.wikipedia.org/wiki/Mobile_broadband 
Question : Does the network bandtwidth (2G/3G/4G) name in CellMapper uses the same grouping of boradband frequenties as group in https://en.wikipedia.org/wiki/Mobile_broadband ? (see screenshot below)

![afbeelding](https://cloud.githubusercontent.com/assets/25255092/22396675/b083c204-e55f-11e6-831e-72192f6c2746.png)

**Comment by olkitu** [comment]
![image](https://cloud.githubusercontent.com/assets/10426342/22396698/94bdf810-e568-11e6-8d4d-acac147e6434.png)

So you see. System Subtype is more accurate information about mobile network generation. 

HSPA+ example is not 4G, it's 3G. DC-HSPA+ mostly phone's not report and we say it's 3G.

LTE, LTE-A is 4G network.

**Comment by olkitu** [comment]
So there summary:

2G - GSM above: GPRS, EDGE
3G - UMTS above: UMTS, HSDPA, HSUPA, HSPA, HSPA+, DC-HSPA+

4G - LTE above: LTE, LTE-A

2G - CDMA above: CDMA, 1xRTT, EVDO, EHRPD

**Comment by alinderom** [comment]
Thanks, Indeed wiki is not to be trusted alle the time. Maybe add the bandtwidth information in your wiki or manual

Thank you very much
