### ISSUE TITLE
DiGI 2G not show correct band Name

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#77]
![photo_2017-02-25_14-27-02](https://cloud.githubusercontent.com/assets/10426342/23331058/8035f4c4-fb66-11e6-812e-34a33758a58c.jpg)

Should be 1800 DCS

**Comment by zivan56** [comment]
This will be fixed in the next beta/version.

**Comment by zivan56** [comment]
Also, the website had this exact same bug...that has been fixed already.
