### ISSUE TITLE
LTE-A reading not working some provider network

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#78]
LTE-A reading not working Elisa Finland networks but working Sonera and DNA Finland network well. 

Tested Nexus 5X and Sony XZ.

**Comment by olkitu** [comment]
Also affected TIM Italian (222-1)

**Comment by zivan56** [comment]
The value is either enabled or disabled from the RIL, so nothing I can do about it.
Ultimately, the manufacturer should fix this. However, since its a hidden API, they probably will not.
