### ISSUE TITLE
Blacklist some EARFCN on 244 - Finland

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#81]
Block some band B7 EARFCN:

DNA 244-12: 2963
Elisa 244-5: 3084
Telia (former Sonera) Finland: 3022

Valid B7 is:
DNA: 2850
Elisa: 3300
Telia: 3050

**Comment by zivan56** [comment]
Don't think blacklisting is the right approach.  Rather, waiting a few seconds before recording after handoff is better.  Can you confirm the latest version still has this issue?  It has a few seconds delay recording on handoff.
