### ISSUE TITLE
Mostly phones report incorrect EARFCN (B7)

### ISSUE THREAD

**Issue by olkitu** [CellMapper/CellMapper-Android-App#82]
Mostly phone's report incorrect EARFCN when handover example.

Affected:

Samsung
OnePlus 3T
Mostly new Android 7+ devices

**Comment by olkitu** [comment]
#81

**Comment by zivan56** [comment]
Not sure what I can do about that?

**Comment by olkitu** [comment]
I do not know either :) It's handover Android Cell ID API issue.
