### ISSUE TITLE
Android trying to restart cellmapper when it exits

### ISSUE THREAD

**Issue by adlr** [CellMapper/CellMapper-Android-App#83]
Hi, I notice on logcat that Android is trying to restart the cellmapper service when it dies. It seems to die by calling Process.killProcess(Process.myPid()). Android thinks the service should still be running and tries to relaunch it. This goes into a launch-die loop and can result in extra battery drain when app should be not running at all!

I am on Google Pixel OS 7.1.2 and CellMapper 5.0.9.

Thanks!

**Comment by adlr** [comment]
Here's a more complete logcat:

04-19 08:51:03.114  1171  5277 I ActivityManager: Process cellmapper.net.cellmapper (pid 21990) has died
04-19 08:51:03.114  1171  5277 D ActivityManager: cleanUpApplicationRecord -- 21990
04-19 08:51:03.114  1171  5277 W ActivityManager: Scheduling restart of crashed service cellmapper.net.cellmapper/.BackgroundService in 1000ms
04-19 08:51:04.153  1171  1199 I ActivityManager: Start proc 22008:cellmapper.net.cellmapper/u0a116 for service cellmapper.net.cellmapper/.BackgroundService
04-19 08:51:04.224 22008 22008 W System  : ClassLoader referenced unknown path: /data/app/cellmapper.net.cellmapper-1/lib/arm64
04-19 08:51:04.261 22008 22008 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
04-19 08:51:04.271 22008 22008 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
04-19 08:51:04.292 22008 22008 I FA      : App measurement is starting up, version: 9452
04-19 08:51:04.292 22008 22008 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
04-19 08:51:04.321 22008 22008 I FirebaseInitProvider: FirebaseApp initialization successful
04-19 08:51:04.328 22008 22008 I Process : Sending signal. PID: 22008 SIG: 9
04-19 08:51:04.342  1171  9730 I ActivityManager: Process cellmapper.net.cellmapper (pid 22008) has died
04-19 08:51:04.342  1171  9730 D ActivityManager: cleanUpApplicationRecord -- 22008
04-19 08:51:04.342  1171  9730 W ActivityManager: Scheduling restart of crashed service cellmapper.net.cellmapper/.BackgroundService in 1000ms
04-19 08:51:05.379  1171  1199 I ActivityManager: Start proc 22027:cellmapper.net.cellmapper/u0a116 for service cellmapper.net.cellmapper/.BackgroundService
04-19 08:51:05.457 22027 22027 W System  : ClassLoader referenced unknown path: /data/app/cellmapper.net.cellmapper-1/lib/arm64
04-19 08:51:05.496 22027 22027 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
04-19 08:51:05.515 22027 22027 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
04-19 08:51:05.531 22027 22027 I FA      : App measurement is starting up, version: 9452
04-19 08:51:05.531 22027 22027 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
04-19 08:51:05.562 22027 22027 I FirebaseInitProvider: FirebaseApp initialization successful
04-19 08:51:05.567 22027 22027 I Process : Sending signal. PID: 22027 SIG: 9
04-19 08:51:05.582  1171  9732 I ActivityManager: Process cellmapper.net.cellmapper (pid 22027) has died
04-19 08:51:05.582  1171  9732 D ActivityManager: cleanUpApplicationRecord -- 22027
04-19 08:51:05.582  1171  9732 W ActivityManager: Scheduling restart of crashed service cellmapper.net.cellmapper/.BackgroundService in 1000ms
04-19 08:51:06.621  1171  1199 I ActivityManager: Start proc 22046:cellmapper.net.cellmapper/u0a116 for service cellmapper.net.cellmapper/.BackgroundService
04-19 08:51:06.704 22046 22046 W System  : ClassLoader referenced unknown path: /data/app/cellmapper.net.cellmapper-1/lib/arm64
04-19 08:51:06.742 22046 22046 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
04-19 08:51:06.758 22046 22046 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
04-19 08:51:06.769 22046 22046 I FA      : App measurement is starting up, version: 9452
04-19 08:51:06.769 22046 22046 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
04-19 08:51:06.799 22046 22046 I FirebaseInitProvider: FirebaseApp initialization successful
04-19 08:51:06.808 22046 22046 I Process : Sending signal. PID: 22046 SIG: 9
04-19 08:51:06.822  1171  9734 I ActivityManager: Process cellmapper.net.cellmapper (pid 22046) has died
04-19 08:51:06.822  1171  9734 D ActivityManager: cleanUpApplicationRecord -- 22046
04-19 08:51:06.823  1171  9734 W ActivityManager: Scheduling restart of crashed service cellmapper.net.cellmapper/.BackgroundService in 1000ms
04-19 08:51:07.839  1171  1199 I ActivityManager: Start proc 22065:cellmapper.net.cellmapper/u0a116 for service cellmapper.net.cellmapper/.BackgroundService
04-19 08:51:07.894 22065 22065 W System  : ClassLoader referenced unknown path: /data/app/cellmapper.net.cellmapper-1/lib/arm64
04-19 08:51:07.924 22065 22065 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
04-19 08:51:07.937 22065 22065 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
04-19 08:51:07.946 22065 22065 I FA      : App measurement is starting up, version: 9452
04-19 08:51:07.946 22065 22065 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
04-19 08:51:07.965 22065 22065 I FirebaseInitProvider: FirebaseApp initialization successful
04-19 08:51:07.971 22065 22065 I Process : Sending signal. PID: 22065 SIG: 9

**Comment by zivan56** [comment]
Thanks, this was a hack for some devices which didn't handle stopping activities/services properly.  I have removed it since it has been a few years since this was last seen.  It will be in the next version.
