### ISSUE TITLE
upload.cellmapper.net "unable to resolve host"

### ISSUE THREAD

**Issue by brycenesbitt** [CellMapper/CellMapper-Android-App#84]
# Impact Version

* CellMapper: App Version: 5.X
* Phone Model: Google Nexus 5X
* Language: en

# Steps to reproduce
Attempt to upload, get error "upload.cellmapper.net" "unable to resolve host" due to network issue.  Once network is back, the error stays, even if you restart the upload.

# Current behavior
No workie

# Expected behavior
Workie

# Video/Screenshot link (optional)

**Comment by olkitu** [comment]
This is DNS error, please check you have internet connection and restart app.

**Comment by brycenesbitt** [comment]
With most apps, once the data connection or wifi comes back, the error goes away. I have found pressing upload again does not clear the error in many cases.  Start an upload, enter airplane mode, then exit airplane mode to demonstrate.

**Comment by olkitu** [comment]
@zivan56 Something should do... Maybe some timeout and then try again?

**Comment by zivan56** [comment]
This is up to OS and Volley library, CellMapper has no control over it unless we write our own HTTP library.

**Comment by brycenesbitt** [comment]
Dropping issue then.

**Comment by brycenesbitt** [comment]
I exit app and restart to get around this issue.
