### ISSUE TITLE
MNC code clutter hides top carriers

### ISSUE THREAD

**Issue by brycenesbitt** [CellMapper/CellMapper-Android-App#86]
As evidenced by this review:
https://play.google.com/store/apps/details?id=cellmapper.net.cellmapper&reviewId=Z3A6QU9xcFRPRndaaU1YaXRXXzZYS0NUX3JWRDVueU5hcTBINHRFeEtRczFsckR1R19QSmZOaDVGdWJjbXFjWHp4aUMyNkxxWDVIWGVvWF9IUy1ZeFJPTWh3&hl=en
"The app was totally useless to me. I wanted to find Verizon towers and Verizon isn't even one of the choices you can search for. I"

The MNC selection for the USA is confusing.  The USA has multiple country codes, and the big carriers like Verizon are buried in the list.

Perhaps the CellMaper MNC pulldown could be sorted by volume of data collected, or alphabetically.
Could all the USA MCC codes (310,31,,312,316) be grouped as one item?

**Comment by zivan56** [comment]
This will be supported in the future maps.
For now, you can right click on a country and select provider, which is pretty trivial even for non-technical people, and it is already sorted by volume of data.

**Comment by brycenesbitt** [comment]
I'm quite technical.  Yet I found it confusing at first also.

People are less likely to discover the right click on map, when the dialog box starts with "Select a country from the side menu....".

----------------
But here I was really referring to the app, where the providers are not sorted by volume, and "searching for service" is more prominent than "Verizon".

--------------
To get people started, having a default of "show all providers" might help.

**Comment by brycenesbitt** [comment]
Having the default be "all carriers" helps, in that data will be shown to a first time user, rather than blank.

**Comment by olkitu** [comment]
@brycenesbitt  it bit confusing show all tower same time... It's also not possible because your browser will crash... (too much data). But we trying make this simple for new user on beta map.

**Comment by brycenesbitt** [comment]
You can show all coverage, and select towers.

On the new map, it is better, but load time is very slow in the USA with
all the carriers.
Having "top 5" then "more" would be better.
