### ISSUE TITLE
Map mode touch does not remember current provider

### ISSUE THREAD

**Issue by brycenesbitt** [CellMapper/CellMapper-Android-App#94]
# Impact Version
* CellMapper: App Version: 5.1.3
* Phone Model: Google Nexus 5x
* Language: en

# Current behavior
In map mode, each time I touch to select a new MCC/MNC, the Country pulldown defaults to 310.
This makes switching between bands a multi step process (instead of just setting a new band, I have to set MCC MNC and BAND).

# Expected behavior
I expect the pulldowns to reflect the currently shown MCC/MNC/BAND.
Same goes for if I select "current provider", the next time I touch, I expect it to show MCC/MNC/Band of the current provider.

**Comment by zivan56** [comment]
This is working as designed.
The geolocation to MCC mapping cannot work with multiple MCC countries.
Tapping select provider will bring up the last one selected (if ever selected) or your current one.

**Comment by brycenesbitt** [comment]
As of Android beta cellmapper 5.1.3, the app does NOT bring up the last one selected.
